use anyhow::{Context, Result};
use std::collections::HashMap;
use std::path::Path;
use tokio::fs;

pub async fn read_server_properties(path: &Path) -> Result<HashMap<String, String>> {
    let content = fs::read_to_string(path)
        .await
        .context("Failed to read server.properties")?;

    let mut properties = HashMap::new();
    
    for line in content.lines() {
        let line = line.trim();
        
        // Skip comments and empty lines
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        // Parse key=value
        if let Some((key, value)) = line.split_once('=') {
            properties.insert(key.trim().to_string(), value.trim().to_string());
        }
    }

    Ok(properties)
}

pub async fn write_server_properties(
    path: &Path,
    properties: &HashMap<String, String>,
) -> Result<()> {
    let mut lines = Vec::new();
    
    lines.push("#Minecraft server properties".to_string());
    lines.push(format!("#Generated by Minecraft Server Manager"));
    lines.push(String::new());

    // Sort keys for consistent output
    let mut keys: Vec<_> = properties.keys().collect();
    keys.sort();

    for key in keys {
        if let Some(value) = properties.get(key) {
            lines.push(format!("{}={}", key, value));
        }
    }

    let content = lines.join("\n");
    fs::write(path, content)
        .await
        .context("Failed to write server.properties")?;

    Ok(())
}

pub fn get_default_properties(port: u16, max_players: u32) -> HashMap<String, String> {
    let mut props = HashMap::new();
    
    // Basic settings
    props.insert("server-port".to_string(), port.to_string());
    props.insert("max-players".to_string(), max_players.to_string());
    props.insert("online-mode".to_string(), "true".to_string());
    props.insert("white-list".to_string(), "false".to_string());
    props.insert("motd".to_string(), "A Minecraft Server".to_string());
    
    // World settings
    props.insert("level-name".to_string(), "world".to_string());
    props.insert("level-seed".to_string(), String::new());
    props.insert("level-type".to_string(), "default".to_string());
    props.insert("generator-settings".to_string(), String::new());
    props.insert("allow-nether".to_string(), "true".to_string());
    props.insert("generate-structures".to_string(), "true".to_string());
    
    // Gameplay settings
    props.insert("gamemode".to_string(), "survival".to_string());
    props.insert("difficulty".to_string(), "easy".to_string());
    props.insert("hardcore".to_string(), "false".to_string());
    props.insert("pvp".to_string(), "true".to_string());
    props.insert("spawn-monsters".to_string(), "true".to_string());
    props.insert("spawn-animals".to_string(), "true".to_string());
    props.insert("spawn-npcs".to_string(), "true".to_string());
    
    // Performance settings
    props.insert("view-distance".to_string(), "10".to_string());
    props.insert("simulation-distance".to_string(), "10".to_string());
    props.insert("max-tick-time".to_string(), "60000".to_string());
    
    // Network settings
    props.insert("enable-query".to_string(), "false".to_string());
    props.insert("enable-rcon".to_string(), "false".to_string());
    props.insert("enable-status".to_string(), "true".to_string());
    
    // Other settings
    props.insert("allow-flight".to_string(), "false".to_string());
    props.insert("enforce-whitelist".to_string(), "false".to_string());
    props.insert("resource-pack".to_string(), String::new());
    props.insert("resource-pack-sha1".to_string(), String::new());
    props.insert("spawn-protection".to_string(), "16".to_string());
    props.insert("max-world-size".to_string(), "29999984".to_string());
    
    props
}

pub async fn initialize_server_properties(
    server_dir: &Path,
    port: u16,
    max_players: u32,
) -> Result<()> {
    let properties_path = server_dir.join("server.properties");
    let properties = get_default_properties(port, max_players);
    write_server_properties(&properties_path, &properties).await
}
